## Знакомство с Numpy

In [1]:
import numpy as np

Генерация случайной матрицы

Сгенерируйте матрицу, состоящую из 1000 строк и 50 столбцов, элементы которой являются случайными из нормального распределения N(1,100).

Функция для генерации чисел из нормального распределения: np.random.normal

Параметры:

    loc: среднее нормального распределения (в нашем случае 1)
    scale: стандартное отклонение нормального распределения (в нашем случае 10)
    size: размер матрицы (в нашем случае (1000, 50))

In [9]:
X = np.random.normal(loc=1, scale=10, size=(1000, 50))
print(X[:2, :3])

[[  9.02975081  16.82030243   2.97245195]
 [ 10.74505572  -5.0639104   13.16209869]]


Произведите нормировку матрицы из предыдущего задания: вычтите из каждого столбца его среднее значение, а затем поделите на его стандартное отклонение.

Функция для вычисления среднего: np.mean

Функция для вычисления стандартного отклонения: np.std

Первый параметр — матрица, для которой производятся вычисления. Также полезным будет параметр axis, который указывает, по какому измерению вычисляются среднее и стандартное отклонение (если axis=0, то по столбцам, если axis=1, то по строкам; если его не указывать, то данные величины будут вычислены по всей матрице).

In [11]:
m = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_norm = ((X - m) / std)
print(X_norm[:2, :3])

[[ 0.80816096  1.55938861  0.16204051]
 [ 0.98204637 -0.61439598  1.17728788]]


Операции над элементами матрицы

Выведите для заданной матрицы номера строк, сумма элементов в которых превосходит 10.

Функция для подсчета суммы: np.sum

Аргументы аналогичны функциям np.mean и np.std.

К матрицам можно применять логические операции, которые будут применяться поэлементно. Соответственно, результатом такой операции будет матрица такого же размера, в ячейках которой будет записано либо True, либо False. Индексы элементов со значением True можно получить с помощью функции np.nonzero.

In [26]:
#Var 1
sum_in_lines = np.sum(X_norm, axis = 1)
ind_with_need_sum = [i for i in range(len(sum_in_lines)) if sum_in_lines[i] > 10]
print(ind_with_need_sum)
#Var 2
r = np.sum(X_norm, axis=1)
print (np.nonzero(r > 10))

[16, 45, 65, 70, 95, 132, 134, 135, 142, 153, 186, 199, 225, 227, 247, 263, 275, 296, 314, 330, 334, 356, 364, 371, 378, 382, 409, 410, 412, 467, 491, 504, 518, 519, 539, 548, 551, 553, 555, 559, 562, 577, 596, 617, 620, 643, 668, 673, 690, 697, 710, 713, 717, 721, 722, 724, 732, 748, 786, 794, 841, 847, 868, 876, 889, 891, 893, 894, 916, 928, 936, 953, 967, 972, 977, 990, 992]
(array([ 16,  45,  65,  70,  95, 132, 134, 135, 142, 153, 186, 199, 225,
       227, 247, 263, 275, 296, 314, 330, 334, 356, 364, 371, 378, 382,
       409, 410, 412, 467, 491, 504, 518, 519, 539, 548, 551, 553, 555,
       559, 562, 577, 596, 617, 620, 643, 668, 673, 690, 697, 710, 713,
       717, 721, 722, 724, 732, 748, 786, 794, 841, 847, 868, 876, 889,
       891, 893, 894, 916, 928, 936, 953, 967, 972, 977, 990, 992]),)


In [27]:
A = np.eye(3)
B = np.eye(3)
C = np.vstack((A, B))
print(C)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
